// Wakhar WMS Multi-language Translation Dictionary

const translations = {
  en: {
    // Nav Sections
    'Overview': 'Overview',
    'Operations': 'Operations',
    'Finance': 'Finance',
    'Transfer': 'Transfer',
    'Portals': 'Portals',
    'Admin': 'Admin',

    // Nav Items
    'Dashboard': 'Dashboard',
    'Commodity Intake': 'Commodity Intake',
    'Inventory': 'Inventory',
    'Dispatch': 'Dispatch',
    'Grading & QC': 'Grading & QC',
    'Warehouse Receipts': 'Warehouse Receipts',
    'Market Linkage': 'Market Linkage',
    'FPO → Aggregator': 'FPO → Aggregator',
    'Stock Verification': 'Stock Verification',
    'Farmer Portal': 'Farmer Portal',
    'Aggregator View': 'Aggregator View',
    'Warehouses': 'Warehouses',
    'Reports': 'Reports',
    'Integrations': 'Integrations',

    // Common Labels
    'Lot ID': 'Lot ID',
    'Farmer': 'Farmer',
    'Farmer ID': 'Farmer ID',
    'Commodity': 'Commodity',
    'Variety': 'Variety',
    'Quantity': 'Quantity',
    'Moisture': 'Moisture',
    'Grade': 'Grade',
    'Warehouse': 'Warehouse',
    'Status': 'Status',
    'Date': 'Date',
    'Action': 'Action',
    'Price': 'Price',
    'Value': 'Value',
    'Variance': 'Variance',
    'System Qty': 'System Qty',
    'Physical Qty': 'Physical Qty',
    'Lien Status': 'Lien Status',
    'Due Date': 'Due Date',

    // Statuses
    'Available': 'Available',
    'Reserved': 'Reserved',
    'Returned': 'Returned',
    'QC Pending': 'QC Pending',
    'Delivered': 'Delivered',
    'In Transit': 'In Transit',
    'Scheduled': 'Scheduled',
    'Accepted': 'Accepted',
    'OK': 'OK',
    'Variance Status': 'Variance',

    // Crops
    'Rice': 'Rice',
    'Wheat': 'Wheat',
    'Soybean': 'Soybean',
    'Onion': 'Onion',
    'Groundnut': 'Groundnut',
    
    // Additional exact matches
    'Deposits & Withdrawals': 'Deposits & Withdrawals',
    'Warehouse Network': 'Warehouse Network',
    'Logistics': 'Logistics',
    'Trade & Analytics': 'Trade & Analytics',
    'Stock & Orders': 'Stock & Orders',
    'Operating Hours': 'Operating Hours',
    'Contact Info': 'Contact Info',
    'Permitted Commodities': 'Permitted Commodities',
    'Geo-Coordinates': 'Geo-Coordinates',
    'Warehouse Type': 'Warehouse Type',
    'FPO-level': 'FPO-level',
    'Aggregator-level': 'Aggregator-level',
    'Cold storage': 'Cold storage',
    'Zones, Racks, Bins': 'Zones, Racks, Bins',
    'Assigned to': 'Assigned FPO/Region',
    'Intake Gate-In': 'Intake Gate-In',
    'Quality Grading': 'Quality Grading',
    'Warehouse Receipt': 'Warehouse Receipt',
    'Fulfillment / Dispatch': 'Fulfillment / Dispatch',

    // Exact matches for dynamic sections
    'Select Farmer Profile': 'Select Farmer Profile',
    'Step 1 of 4: Search and link depositor': 'Step 1 of 4: Search and link depositor',
    'Scan Booking QR': 'Scan Booking QR',
    'Walk-In': 'Walk-In',
    'Pre-Registered Booking': 'Pre-Registered Booking',
    'Active Booking References *': 'Active Booking References *',
    '-- Select Booking Ref --': '-- Select Booking Ref --',
    'Registered Farmer': 'Registered Farmer',
    'Mobile Number': 'Mobile Number',
    'Aadhaar Number': 'Aadhaar Number',
    'Commodity & Storage specs': 'Commodity & Storage specs',
    'Step 2 of 4: Input weight, source address & warehouse target': 'Step 2 of 4: Input weight, source address & warehouse target',
    'Target Warehouse': 'Target Warehouse',
    'Commodity Type': 'Commodity Type',
    'Total Quantity (kg)': 'Total Quantity (kg)',
    'Bag Count': 'Bag Count',
    'Zone / Storage Rack': 'Zone / Storage Rack',
    'Farm Source Geo-coordinates (GPS for tracking)': 'Farm Source Geo-coordinates (GPS for tracking)',
    'Quality Assurance Lab Parameters': 'Quality Assurance Lab Parameters',
    'Step 3 of 4: Dry matter analysis and sensor checks': 'Step 3 of 4: Dry matter analysis and sensor checks',
    'Moisture Content (%)': 'Moisture Content (%)',
    'Foreign Matter / Impurities (%)': 'Foreign Matter / Impurities (%)',
    'Auto Grading Computation Engine': 'Auto Grading Computation Engine',
    'Computed Quality Grade:': 'Computed Quality Grade:',
    'Remarks / Inspection Notes': 'Remarks / Inspection Notes',
    'Warehouse Receipt Generation': 'Warehouse Receipt Generation',
    'Step 4 of 4: Preview e-WR parameters before authorization': 'Step 4 of 4: Preview e-WR parameters before authorization',
    'WAKHAR DIGITAL WAREHOUSE DEPOSIT RECEIPT': 'WAKHAR DIGITAL WAREHOUSE DEPOSIT RECEIPT',
    'Farmer Information': 'Farmer Information',
    'Deposit Details': 'Deposit Details',
    'Pledge Status': 'Pledge Status',
    'None (Negotiable e-WR)': 'None (Negotiable e-WR)',
    'Authorized Signature': 'Authorized Signature',
    'System Generated Receipt - WDRA Compliant': 'System Generated Receipt - WDRA Compliant',
    'Authorize & Register Intake': 'Authorize & Register Intake',
    'Next Step': 'Next Step',
    'Back': 'Back',
    'New Intake': 'New Intake',
    'Search farmer, village, phone...': 'Search farmer, village, phone...',
    
    // Dashboard exact matches
    'My Deposited Balance': 'My Deposited Balance',
    'Active in storage': 'Active in storage',
    'My Warehouse Receipts': 'My Warehouse Receipts',
    'Pledged Lien Loans': 'Pledged Lien Loans',
    'Net Asset Equity Value': 'Net Asset Equity Value',
    'My e-WR Loan status references': 'My e-WR Loan status references',
    'Quick Operations': 'Quick Operations',
    'Stock by Commodity': 'Stock by Commodity',
    'Weekly Deposit Volume': 'Weekly Deposit Volume',
    'Live Dispatch Tracking': 'Live Dispatch Tracking',
    'Recent Activity Logs': 'Recent Activity Logs',
    'Linked FPO Warehouse Capacities': 'Linked FPO Warehouse Capacities',
    'Aggregator Operations': 'Aggregator Operations',
    'Active Transits': 'Active Transits',
    'eNAM Price Fluctuation Benchmarks': 'eNAM Price Fluctuation Benchmarks',
    'Buyer Actions': 'Buyer Actions',
    'outstanding balance': 'outstanding balance',
    'Outstanding Invoices': 'Outstanding Invoices',
    'Pending Payments': 'Pending Payments',
    'Total Value Locked': 'Total Value Locked',
    'Estimated net worth': 'Estimated net worth',

    // Other screens
    'Third-party Gateways & IoT Connectors': 'Third-party Gateways & IoT Connectors',
    'Initiate FPO Transfer': 'Initiate FPO Transfer',
    'Consolidated Goods Receipt Note (GRN) Ledger': 'Consolidated Goods Receipt Note (GRN) Ledger',
    'Transfer History': 'Transfer History',
    'GRN Verification & Verification —': 'GRN Verification & Verification —',
    'Active Cycle Count — Wai FPO': 'Active Cycle Count — Wai FPO',
    'Variance Report History': 'Variance Report History',
    'Listed e-WR Crop Inventory (Mandi Rates Linked)': 'Listed e-WR Crop Inventory (Mandi Rates Linked)',
    'Create Purchase Order': 'Create Purchase Order',
    'Purchase Order Registry': 'Purchase Order Registry',
    'DBT Settlement & e-WR Release Log': 'DBT Settlement & e-WR Release Log',
    'New Commodity Intake Wizard': 'New Commodity Intake Wizard',
    'Network Capacity Performance': 'Network Capacity Performance',
    'Commodity Mandi Price Trends (Last 6 Months)': 'Commodity Mandi Price Trends (Last 6 Months)',
    'Deposited Commodity History': 'Deposited Commodity History',
    'Submit Outbound Request': 'Submit Outbound Request',
    'Withdrawal Activity Log': 'Withdrawal Activity Log',
    '👤 Personal Details': '👤 Personal Details',
    '💳 Bank Account Details': '💳 Bank Account Details',
    '🌾 Linked FPO Center': '🌾 Linked FPO Center',
    'QC Inspection Database': 'QC Inspection Database',
    'Lot Inspector': 'Lot Inspector',
    'Traccar Live Fleet Tracking': 'Traccar Live Fleet Tracking',
    'Route Timeline Tracker': 'Route Timeline Tracker',
    'Aggregator Dashboard': 'Aggregator Dashboard',
    'Multi-Warehouse Stock Rollup': 'Multi-Warehouse Stock Rollup',
    'Live In-Transit Tracking (Traccar)': 'Live In-Transit Tracking (Traccar)',
    'Bulk Dispatch to Market': 'Bulk Dispatch to Market',
    'Switch Perspective': 'Switch Perspective',
    'Exit / Switch Role': 'Exit / Switch Role',
    'Search farmers, lots, WR…': 'Search farmers, lots, WR…',
    'System Alert logs': 'System Alert logs',
    'Acknowledge All': 'Acknowledge All',
    'All stored commodity moisture parameters conform with optimal levels.': 'All stored commodity moisture parameters conform with optimal levels.',

    // Newly added exact matches for complete translation
    'My Deposits': 'My Deposits',
    'Withdrawal Requests': 'Withdrawal Requests',
    'Farmer Profile': 'Farmer Profile',
    'Multi-Warehouse View': 'Multi-Warehouse View',
    'Transfer Management': 'Transfer Management',
    'Dispatch Tracking': 'Dispatch Tracking',
    'Analytics': 'Analytics',
    'Available Stock': 'Available Stock',
    'Purchase Orders': 'Purchase Orders',
    'Goods Receipt Note (GRN)': 'Goods Receipt Note (GRN)',
    'FPO Manager': 'FPO Manager',
    'Farmer (FM-00412)': 'Farmer (FM-00412)',
    'Aggregator Buyer': 'Aggregator Buyer',
    'Market Partner': 'Market Partner',
    'LINKED FPO COORDINATION OFFICE': 'LINKED FPO COORDINATION OFFICE',
    'Wai Farmer Producer Organization': 'Wai Farmer Producer Organization',
    'Manager: Rajesh Bhosale': 'Manager: Rajesh Bhosale',
    'Office Hotlines:': 'Office Hotlines:',
    'Browse ledger': 'Browse ledger',
    'Withdrawals': 'Withdrawals',
    'Initiate request': 'Initiate request',
    'WR Receipts': 'WR Receipts',
    'Apply pledge': 'Apply pledge',
    'My Profile': 'My Profile',
    'Bank & FPO Details': 'Bank & FPO Details',
    'Eligible': 'Eligible',
    'None': 'None',
    'Active': 'Active'
  },
  mr: {
    // Nav Sections
    'Overview': 'आढावा',
    'Operations': 'कामकाज',
    'Finance': 'वित्त पुरवठा',
    'Transfer': 'हस्तांतरण',
    'Portals': 'पोर्टल्स',
    'Admin': 'प्रशासन',

    // Nav Items
    'Dashboard': 'डॅशबोर्ड',
    'Commodity Intake': 'धान्य आवक',
    'Inventory': 'इन्व्हेंटरी Ledger',
    'Dispatch': 'माल प्रेषण (Dispatch)',
    'Grading & QC': 'प्रतवारी आणि QC',
    'Warehouse Receipts': 'गोदाम पावती (e-WR)',
    'Market Linkage': 'बाजार जोडणी',
    'FPO → Aggregator': 'FPO → खरेदीदार',
    'Stock Verification': 'भौतिक साठा तपासणी',
    'Farmer Portal': 'शेतकरी पोर्टल',
    'Aggregator View': 'एकत्रित डॅशबोर्ड',
    'Warehouses': 'गोदाम व्यवस्थापन',
    'Reports': 'अहवाल व विश्लेषण',
    'Integrations': 'कनेक्टर्स / IoT',

    // Common Labels
    'Lot ID': 'लॉट आयडी',
    'Farmer': 'शेतकरी',
    'Farmer ID': 'शेतकरी आयडी',
    'Commodity': 'पीक / धान्य',
    'Variety': 'वाण (Variety)',
    'Quantity': 'वजन (किलोग्रॅम)',
    'Moisture': 'आर्द्रता (Moisture %)',
    'Grade': 'प्रत (Grade)',
    'Warehouse': 'गोदाम स्थान',
    'Status': 'स्थिती',
    'Date': 'दिनांक',
    'Action': 'कृती',
    'Price': 'बाजार भाव',
    'Value': 'एकूण किंमत',
    'Variance': 'फरक (Variance)',
    'System Qty': 'नोंदीतील वजन',
    'Physical Qty': 'प्रत्यक्ष वजन',
    'Lien Status': 'कर्ज तारण स्थिती',
    'Due Date': 'देय तारीख',

    // Statuses
    'Available': 'उपलब्ध',
    'Reserved': 'राखीव',
    'Returned': 'परत केले',
    'QC Pending': 'QC प्रलंबित',
    'Delivered': 'पोहोचले',
    'In Transit': 'मार्गावर',
    'Scheduled': 'नियोजित',
    'Accepted': 'स्वीकृत',
    'OK': 'योग्य',
    'Variance Status': 'तफावत आढळली',

    // Crops
    'Rice': 'तांदूळ',
    'Wheat': 'गहू',
    'Soybean': 'सोयाबीन',
    'Onion': 'कांदा',
    'Groundnut': 'भुईमूग',
    
    // Additional exact matches
    'Deposits & Withdrawals': 'ठेवी आणि निकास',
    'Warehouse Network': 'गोदाम नेटवर्क',
    'Logistics': 'लॉजिस्टिक्स',
    'Trade & Analytics': 'व्यापार आणि विश्लेषण',
    'Stock & Orders': 'साठा आणि ऑर्डर्स',
    'Operating Hours': 'कामाच्या वेळा',
    'Contact Info': 'संपर्क माहिती',
    'Permitted Commodities': 'परवानगी असलेल्या पिके',
    'Geo-Coordinates': 'भौगोलिक निर्देशक',
    'Warehouse Type': 'गोदामाचा प्रकार',
    'FPO-level': 'FPO-स्तर',
    'Aggregator-level': 'संकलक-स्तर',
    'Cold storage': 'शीतगृह (Cold Storage)',
    'Zones, Racks, Bins': 'झोन, रॅक आणि बिन्स',
    'Assigned to': 'नियुक्त FPO',
    'Intake Gate-In': 'धान्य आवक गेट-इन',
    'Quality Grading': 'प्रतवारी आणि QC',
    'Warehouse Receipt': 'गोदाम पावती',
    'Fulfillment / Dispatch': 'माल पाठवणे / वितरण',

    // Exact matches for dynamic sections
    'Select Farmer Profile': 'शेतकरी प्रोफाइल निवडा',
    'Step 1 of 4: Search and link depositor': 'पायरी १ पैकी ४: शोध आणि जमाकर्ता लिंक करा',
    'Scan Booking QR': 'बुकिंग क्यूआर स्कॅन करा',
    'Walk-In': 'थेट आवक (Walk-In)',
    'Pre-Registered Booking': 'पूर्व-नोंदणीकृत बुकिंग',
    'Active Booking References *': 'सक्रिय बुकिंग संदर्भ *',
    '-- Select Booking Ref --': '-- बुकिंग संदर्भ निवडा --',
    'Registered Farmer': 'नोंदणीकृत शेतकरी',
    'Mobile Number': 'मोबाईल नंबर',
    'Aadhaar Number': 'आधार नंबर',
    'Commodity & Storage specs': 'धान्य आणि साठा तपशील',
    'Step 2 of 4: Input weight, source address & warehouse target': 'पायरी २ पैकी ४: वजन, स्रोत आणि गोदाम निवडा',
    'Target Warehouse': 'लक्ष्य गोदाम',
    'Commodity Type': 'धान्याचा प्रकार',
    'Total Quantity (kg)': 'एकूण वजन (किलो)',
    'Bag Count': 'गोण्यांची संख्या',
    'Zone / Storage Rack': 'झोन / स्टोरेज रॅक',
    'Farm Source Geo-coordinates (GPS for tracking)': 'शेत स्रोत भौगोलिक निर्देशक (GPS)',
    'Quality Assurance Lab Parameters': 'गुणवत्ता हमी लॅब मापदंड',
    'Step 3 of 4: Dry matter analysis and sensor checks': 'पायरी ३ पैकी ४: विश्लेषण आणि सेन्सर तपासणी',
    'Moisture Content (%)': 'आर्द्रता प्रमाण (%)',
    'Foreign Matter / Impurities (%)': 'कचरा / अशुद्धता (%)',
    'Auto Grading Computation Engine': 'स्वयंचलित प्रतवारी गणना इंजिन',
    'Computed Quality Grade:': 'गणना केलेली गुणवत्ता श्रेणी:',
    'Remarks / Inspection Notes': 'शेरा / तपासणी नोंदी',
    'Warehouse Receipt Generation': 'गोदाम पावती निर्मिती',
    'Step 4 of 4: Preview e-WR parameters before authorization': 'पायरी ४ पैकी ४: मंजुरीपूर्वी ई-डब्ल्यूआरचे पूर्वावलोकन',
    'WAKHAR DIGITAL WAREHOUSE DEPOSIT RECEIPT': 'वाखर डिजिटल गोदाम ठेव पावती',
    'Farmer Information': 'शेतकऱ्याची माहिती',
    'Deposit Details': 'ठेव तपशील',
    'Pledge Status': 'तारण स्थिती',
    'None (Negotiable e-WR)': 'काहीही नाही (हस्तांतरणीय e-WR)',
    'Authorized Signature': 'अधिकृत स्वाक्षरी',
    'System Generated Receipt - WDRA Compliant': 'सिस्टम व्युत्पन्न पावती - WDRA सुसंगत',
    'Authorize & Register Intake': 'मंजूर आणि आवक नोंदवा',
    'Next Step': 'पुढील पाऊल',
    'Back': 'मागे',
    'New Intake': 'नवीन आवक',
    'Search farmer, village, phone...': 'शेतकरी, गाव, फोन शोधा...',
    
    // Dashboard exact matches
    'My Deposited Balance': 'माझा साठवलेला माल',
    'Active in storage': 'गोदामामध्ये सक्रिय',
    'My Warehouse Receipts': 'माझ्या गोदाम पावत्या',
    'Pledged Lien Loans': 'तारण कर्ज',
    'Net Asset Equity Value': 'निव्वळ मालमत्ता मूल्य',
    'My e-WR Loan status references': 'माझे ई-डब्ल्यूआर कर्ज तपशील',
    'Quick Operations': 'जलद ऑपरेशन्स',
    'Stock by Commodity': 'पिकानुसार साठा',
    'Weekly Deposit Volume': 'साप्ताहिक आवक प्रमाण',
    'Live Dispatch Tracking': 'लाइव्ह प्रेषण ट्रॅकिंग',
    'Recent Activity Logs': 'अलीकडील क्रियाकलाप लॉग',
    'Linked FPO Warehouse Capacities': 'लिंक केलेल्या गोदामांची क्षमता',
    'Aggregator Operations': 'संकलक ऑपरेशन्स',
    'Active Transits': 'सक्रिय मार्गक्रमण (Transits)',
    'eNAM Price Fluctuation Benchmarks': 'ई-नाम बाजारभाव बेंचमार्क',
    'Buyer Actions': 'खरेदीदार ऑपरेशन्स',
    'outstanding balance': 'थकीत शिल्लक',
    'Outstanding Invoices': 'थकीत बिले',
    'Pending Payments': 'प्रलंबित देयके',
    'Total Value Locked': 'एकूण मूल्य लॉक केलेले',
    'Estimated net worth': 'अंदाजित निव्वळ मूल्य',

    // Other screens
    'Third-party Gateways & IoT Connectors': 'तृतीय-पक्ष गेटवे आणि आयओटी कनेक्टर्स',
    'Initiate FPO Transfer': 'FPO हस्तांतरण सुरू करा',
    'Consolidated Goods Receipt Note (GRN) Ledger': 'एकत्रित वस्तू पावती (GRN) लेजर',
    'Transfer History': 'हस्तांतरण इतिहास',
    'GRN Verification & Verification —': 'GRN पडताळणी आणि सत्यापन —',
    'Active Cycle Count — Wai FPO': 'सक्रिय भौतिक तपासणी — वाई FPO',
    'Variance Report History': 'तफावत अहवाल इतिहास',
    'Listed e-WR Crop Inventory (Mandi Rates Linked)': 'नोंदणीकृत ई-डब्ल्यूआर धान्य यादी (मंडी दरांशी जोडलेली)',
    'Create Purchase Order': 'खरेदी ऑर्डर तयार करा',
    'Purchase Order Registry': 'खरेदी ऑर्डर नोंदणी',
    'DBT Settlement & e-WR Release Log': 'थेट बँक हस्तांतरण (DBT) आणि ई-डब्ल्यूआर प्रकाशन लॉग',
    'New Commodity Intake Wizard': 'नवीन धान्य आवक विझार्ड',
    'Network Capacity Performance': 'नेटवर्क क्षमता कार्यप्रदर्शन',
    'Commodity Mandi Price Trends (Last 6 Months)': 'धान्य मंडी भाव कल (गेले ६ महिने)',
    'Deposited Commodity History': 'ठेवलेल्या धान्याचा इतिहास',
    'Submit Outbound Request': 'निकासीसाठी विनंती सादर करा',
    'Withdrawal Activity Log': 'निकासी क्रियाकलाप लॉग',
    '👤 Personal Details': '👤 वैयक्तिक तपशील',
    '💳 Bank Account Details': '💳 बँक खाते तपशील',
    '🌾 Linked FPO Center': '🌾 लिंक केलेले FPO केंद्र',
    'QC Inspection Database': 'QC तपासणी डेटाबेस',
    'Lot Inspector': 'लॉट निरीक्षक',
    'Traccar Live Fleet Tracking': 'ट्रॅकार लाइव्ह फ्लीट ट्रॅकिंग',
    'Route Timeline Tracker': 'मार्ग टाइमलाइन ट्रॅकर',
    'Aggregator Dashboard': 'संकलक डॅशबोर्ड',
    'Multi-Warehouse Stock Rollup': 'बहु-गोदाम साठा संकलन',
    'Live In-Transit Tracking (Traccar)': 'लाइव्ह इन-ट्रांझिट ट्रॅकिंग (Traccar)',
    'Bulk Dispatch to Market': 'बाजारात घाऊक प्रेषण',
    'Switch Perspective': 'वापरकर्ता बदला',
    'Exit / Switch Role': 'बाहेर पडा / भूमिका बदला',
    'Search farmers, lots, WR…': 'शेतकरी, लॉट, ई-डब्ल्यूआर शोधा…',
    'System Alert logs': 'सिस्टम चेतावणी लॉग',
    'Acknowledge All': 'सर्व मान्य करा',
    'All stored commodity moisture parameters conform with optimal levels.': 'साठवलेल्या धान्याचे सर्व आर्द्रता मापदंड योग्य पातळीत आहेत.',

    // Newly added exact matches for complete translation
    'My Deposits': 'माझ्या ठेवी',
    'Withdrawal Requests': 'निकासी विनंत्या',
    'Farmer Profile': 'शेतकरी प्रोफाइल',
    'Multi-Warehouse View': 'बहु-गोदाम दृश्य',
    'Transfer Management': 'हस्तांतरण व्यवस्थापन',
    'Dispatch Tracking': 'प्रेषण ट्रॅकिंग',
    'Analytics': 'विश्लेषण',
    'Available Stock': 'उपलब्ध साठा',
    'Purchase Orders': 'खरेदी ऑर्डर्स',
    'Goods Receipt Note (GRN)': 'वस्तू पावती नोंद (GRN)',
    'FPO Manager': 'FPO व्यवस्थापक',
    'Farmer (FM-00412)': 'शेतकरी (FM-00412)',
    'Aggregator Buyer': 'संकलक खरेदीदार',
    'Market Partner': 'बाजार भागीदार',
    'LINKED FPO COORDINATION OFFICE': 'लिंक केलेले FPO समन्वय कार्यालय',
    'Wai Farmer Producer Organization': 'वाई शेतकरी उत्पादक संघटना (FPO)',
    'Manager: Rajesh Bhosale': 'व्यवस्थापक: राजेश भोसले',
    'Office Hotlines:': 'कार्यालय संपर्क:',
    'Browse ledger': 'लेजर ब्राउझ करा',
    'Withdrawals': 'निकासी',
    'Initiate request': 'विनंती सुरू करा',
    'WR Receipts': 'गोदाम पावत्या (e-WR)',
    'Apply pledge': 'तारण कर्ज अर्ज करा',
    'My Profile': 'माझी प्रोफाइल',
    'Bank & FPO Details': 'बँक आणि FPO तपशील',
    'Eligible': 'पात्र',
    'None': 'काहीही नाही',
    'Active': 'सक्रिय'
  },
  hi: {
    // Nav Sections
    'Overview': 'अवलोकन',
    'Operations': 'संचालन',
    'Finance': 'वित्त व्यवस्था',
    'Transfer': 'स्थानांतरण',
    'Portals': 'पोर्टल',
    'Admin': 'प्रशासन',

    // Nav Items
    'Dashboard': 'डैशबोर्ड',
    'Commodity Intake': 'अनाज आवक',
    'Inventory': 'माल सूची (Inventory)',
    'Dispatch': 'निकास (Dispatch)',
    'Grading & QC': 'ग्रेडिंग और गुणवत्ता',
    'Warehouse Receipts': 'गोदाम रसीद (e-WR)',
    'Market Linkage': 'बाजार विपणन',
    'FPO → Aggregator': 'FPO → संकलक',
    'Stock Verification': 'भौतिक सत्यापन',
    'Farmer Portal': 'किसान पोर्टल',
    'Aggregator View': 'कंसोलिडेटेड व्यू',
    'Warehouses': 'गोदाम प्रबंधन',
    'Reports': 'रिपोर्ट एवं विश्लेषण',
    'Integrations': 'एकीकरण (IoT)',

    // Common Labels
    'Lot ID': 'लॉट आईडी',
    'Farmer': 'किसान',
    'Farmer ID': 'किसान आईडी',
    'Commodity': 'जिंस (फसल)',
    'Variety': 'किस्म',
    'Quantity': 'वजन (किग्रा)',
    'Moisture': 'नमी % (Moisture)',
    'Grade': 'श्रेणी (Grade)',
    'Warehouse': 'गोदाम स्थान',
    'Status': 'स्थिति',
    'Date': 'दिनांक',
    'Action': 'कार्रवाई',
    'Price': 'बाजार भाव',
    'Value': 'कुल मूल्य',
    'Variance': 'अंतर (Variance)',
    'System Qty': 'सिस्टम वजन',
    'Physical Qty': 'वास्तविक वजन',
    'Lien Status': 'बंधक स्थिति',
    'Due Date': 'नियत तिथि',

    // Statuses
    'Available': 'उपलब्ध',
    'Reserved': 'आरक्षित',
    'Returned': 'वापस किया',
    'QC Pending': 'जांच लंबित',
    'Delivered': 'डिलिवर हुआ',
    'In Transit': 'मार्ग में',
    'Scheduled': 'अनुसूचित',
    'Accepted': 'स्वीकृत',
    'OK': 'सही',
    'Variance Status': 'अंतर मिला',

    // Crops
    'Rice': 'चावल',
    'Wheat': 'गेहूं',
    'Soybean': 'सोयाबीन',
    'Onion': 'प्याज़',
    'Groundnut': 'मूंगफली',
    
    // Additional exact matches
    'Deposits & Withdrawals': 'जमा और निकासी',
    'Warehouse Network': 'गोदाम नेटवर्क',
    'Logistics': 'लॉजिस्टिक्स',
    'Trade & Analytics': 'व्यापार और विश्लेषण',
    'Stock & Orders': 'स्टॉक और ऑर्डर',
    'Operating Hours': 'कार्य समय',
    'Contact Info': 'संपर्क सूत्र',
    'Permitted Commodities': 'अनुमत जिंसें',
    'Geo-Coordinates': 'भू-निर्देशांक',
    'Warehouse Type': 'गोदाम का प्रकार',
    'FPO-level': 'FPO-स्तर',
    'Aggregator-level': 'संकलक-स्तर',
    'Cold storage': 'शीतगृह (Cold Storage)',
    'Zones, Racks, Bins': 'ज़ोन, रैक और बिन्स',
    'Assigned to': 'संबद्ध FPO',
    'Intake Gate-In': 'अनाज आवक गेट-इन',
    'Quality Grading': 'ग्रेडिंग और गुणवत्ता',
    'Warehouse Receipt': 'गोदाम रसीद',
    'Fulfillment / Dispatch': 'निकास / वितरण',

    // Exact matches for dynamic sections
    'Select Farmer Profile': 'किसान प्रोफाइल चुनें',
    'Step 1 of 4: Search and link depositor': 'चरण 1 का 4: खोजें और जमाकर्ता को लिंक करें',
    'Scan Booking QR': 'बुकिंग क्यूआर स्कैन करें',
    'Walk-In': 'सीधे आवक (Walk-In)',
    'Pre-Registered Booking': 'पूर्व-पंजीकृत बुकिंग',
    'Active Booking References *': 'सक्रिय बुकिंग संदर्भ *',
    '-- Select Booking Ref --': '-- बुकिंग संदर्भ चुनें --',
    'Registered Farmer': 'पंजीकृत किसान',
    'Mobile Number': 'मोबाइल नंबर',
    'Aadhaar Number': 'आधार नंबर',
    'Commodity & Storage specs': 'जिंस और भंडारण विवरण',
    'Step 2 of 4: Input weight, source address & warehouse target': 'चरण 2 का 4: वजन, स्रोत और गोदाम चुनें',
    'Target Warehouse': 'लक्ष्य गोदाम',
    'Commodity Type': 'जिंस का प्रकार',
    'Total Quantity (kg)': 'कुल वजन (किग्रा)',
    'Bag Count': 'बोरी की संख्या',
    'Zone / Storage Rack': 'ज़ोन / स्टोरेज रैक',
    'Farm Source Geo-coordinates (GPS for tracking)': 'खेत स्रोत भू-निर्देशांक (GPS)',
    'Quality Assurance Lab Parameters': 'गुणवत्ता आश्वासन लैब पैरामीटर',
    'Step 3 of 4: Dry matter analysis and sensor checks': 'चरण 3 का 4: विश्लेषण और सेंसर जांच',
    'Moisture Content (%)': 'नमी की मात्रा (%)',
    'Foreign Matter / Impurities (%)': 'विदेशी पदार्थ / अशुद्धियाँ (%)',
    'Auto Grading Computation Engine': 'स्वचालित ग्रेडिंग गणना इंजन',
    'Computed Quality Grade:': 'गणना की गई गुणवत्ता श्रेणी:',
    'Remarks / Inspection Notes': 'टिप्पणी / निरीक्षण नोट्स',
    'Warehouse Receipt Generation': 'गोदाम रसीद निर्माण',
    'Step 4 of 4: Preview e-WR parameters before authorization': 'चरण 4 का 4: मंजूरी से पहले ई-डब्ल्यूआर का पूर्वावलोकन',
    'WAKHAR DIGITAL WAREHOUSE DEPOSIT RECEIPT': 'वाखर डिजिटल गोदाम जमा रसीद',
    'Farmer Information': 'किसान की जानकारी',
    'Deposit Details': 'जमा विवरण',
    'Pledge Status': 'बंधक स्थिति',
    'None (Negotiable e-WR)': 'कोई नहीं (परक्राम्य e-WR)',
    'Authorized Signature': 'अधिकृत हस्ताक्षर',
    'System Generated Receipt - WDRA Compliant': 'सिस्टम जनरेटेड रसीद - WDRA अनुपालन',
    'Authorize & Register Intake': 'स्वीकृत और आवक दर्ज करें',
    'Next Step': 'अगला कदम',
    'Back': 'पीछे',
    'New Intake': 'नई आवक',
    'Search farmer, village, phone...': 'किसान, गाँव, फोन खोजें...',
    
    // Dashboard exact matches
    'My Deposited Balance': 'मेरी जमा शेष राशि',
    'Active in storage': 'गोदाम में सक्रिय',
    'My Warehouse Receipts': 'मेरी गोदाम रसीदें',
    'Pledged Lien Loans': 'बंधक ऋण',
    'Net Asset Equity Value': 'शुद्ध संपत्ति मूल्य',
    'My e-WR Loan status references': 'मेरे ई-डब्ल्यूआर ऋण विवरण',
    'Quick Operations': 'त्वरित संचालन',
    'Stock by Commodity': 'फसल अनुसार स्टॉक',
    'Weekly Deposit Volume': 'साप्ताहिक जमा मात्रा',
    'Live Dispatch Tracking': 'लाइव प्रेषण ट्रैकिंग',
    'Recent Activity Logs': 'हाल की गतिविधियां लॉग',
    'Linked FPO Warehouse Capacities': 'संबद्ध गोदाम क्षमता',
    'Aggregator Operations': 'संकलक संचालन',
    'Active Transits': 'सक्रिय पारगमन',
    'eNAM Price Fluctuation Benchmarks': 'ई-नाम बाजार मूल्य बेंचमार्क',
    'Buyer Actions': 'क्रेता संचालन',
    'outstanding balance': 'बकाया शेष राशि',
    'Outstanding Invoices': 'बकाया बिल',
    'Pending Payments': 'लंबित भुगतान',
    'Total Value Locked': 'कुल लॉक मूल्य',
    'Estimated net worth': 'अनुमानित शुद्ध मूल्य',

    // Other screens
    'Third-party Gateways & IoT Connectors': 'तीसरे पक्ष के गेटवे और आईओटी कनेक्टर्स',
    'Initiate FPO Transfer': 'FPO स्थानांतरण शुरू करें',
    'Consolidated Goods Receipt Note (GRN) Ledger': 'समेकित माल रसीद (GRN) बही',
    'Transfer History': 'स्थानांतरण इतिहास',
    'GRN Verification & Verification —': 'GRN सत्यापन और पुष्टि —',
    'Active Cycle Count — Wai FPO': 'सक्रिय भौतिक सत्यापन — वाई FPO',
    'Variance Report History': 'अंतर रिपोर्ट इतिहास',
    'Listed e-WR Crop Inventory (Mandi Rates Linked)': 'पंजीकृत ई-डब्ल्यूआर अनाज सूची (मंडी दरों से संबद्ध)',
    'Create Purchase Order': 'क्रय आदेश बनाएं',
    'Purchase Order Registry': 'क्रय आदेश रजिस्ट्री',
    'DBT Settlement & e-WR Release Log': 'डीबीटी भुगतान और ई-डब्ल्यूआर रिलीज लॉग',
    'New Commodity Intake Wizard': 'नई जिंस आवक विज़ार्ड',
    'Network Capacity Performance': 'नेटवर्क क्षमता प्रदर्शन',
    'Commodity Mandi Price Trends (Last 6 Months)': 'जिंस मंडी मूल्य रुझान (पिछले 6 महीने)',
    'Deposited Commodity History': 'जमा जिंस इतिहास',
    'Submit Outbound Request': 'निकासी अनुरोध सबमिट करें',
    'Withdrawal Activity Log': 'निकासी गतिविधि लॉग',
    '👤 Personal Details': '👤 व्यक्तिगत विवरण',
    '💳 Bank Account Details': '💳 बैंक खाता विवरण',
    '🌾 Linked FPO Center': '🌾 संबद्ध FPO केंद्र',
    'QC Inspection Database': 'QC निरीक्षण डेटाबेस',
    'Lot Inspector': 'लॉट निरीक्षक',
    'Traccar Live Fleet Tracking': 'ट्रेकार लाइव्ह फ्लीट ट्रैकिंग',
    'Route Timeline Tracker': 'मार्ग समयरेखा ट्रैकर',
    'Aggregator Dashboard': 'संकलक डैशबोर्ड',
    'Multi-Warehouse Stock Rollup': 'बहु-गोदाम स्टॉक संकलन',
    'Live In-Transit Tracking (Traccar)': 'लाइव इन-ट्रांजिट ट्रैकिंग (Traccar)',
    'Bulk Dispatch to Market': 'बाजार में थोक प्रेषण',
    'Switch Perspective': 'उपयोगकर्ता बदलें',
    'Exit / Switch Role': 'बाहर निकलें / भूमिका बदलें',
    'Search farmers, lots, WR…': 'किसान, लॉट, ई-डब्ल्यूआर खोजें…',
    'System Alert logs': 'सिस्टम चेतावनी लॉग',
    'Acknowledge All': 'सभी स्वीकार करें',
    'All stored commodity moisture parameters conform with optimal levels.': 'संग्रहीत जिंस के सभी नमी पैरामीटर अनुकूल स्तर पर हैं.',

    // Newly added exact matches for complete translation
    'My Deposits': 'मेरी जमा राशि',
    'Withdrawal Requests': 'निकासी अनुरोध',
    'Farmer Profile': 'किसान प्रोफाइल',
    'Multi-Warehouse View': 'बहु-गोदाम दृश्य',
    'Transfer Management': 'स्थानांतरण प्रबंधन',
    'Dispatch Tracking': 'प्रेषण ट्रैकिंग',
    'Analytics': 'विश्लेषण',
    'Available Stock': 'उपलब्ध स्टॉक',
    'Purchase Orders': 'क्रय आदेश',
    'Goods Receipt Note (GRN)': 'माल रसीद नोट (GRN)',
    'FPO Manager': 'FPO प्रबंधक',
    'Farmer (FM-00412)': 'किसान (FM-00412)',
    'Aggregator Buyer': 'संकलक क्रेता',
    'Market Partner': 'बाजार भागीदार',
    'LINKED FPO COORDINATION OFFICE': 'संबद्ध FPO समन्वय कार्यालय',
    'Wai Farmer Producer Organization': 'वाई किसान उत्पादक संगठन (FPO)',
    'Manager: Rajesh Bhosale': 'प्रबंधक: राजेश भोसले',
    'Office Hotlines:': 'कार्यालय हेल्पलाइन:',
    'Browse ledger': 'बही देखें',
    'Withdrawals': 'निकासी',
    'Initiate request': 'अनुरोध शुरू करें',
    'WR Receipts': 'गोदाम रसीद (e-WR)',
    'Apply pledge': 'ऋण के लिए आवेदन करें',
    'My Profile': 'मेरी प्रोफाइल',
    'Bank & FPO Details': 'बैंक और FPO विवरण',
    'Eligible': 'पात्र',
    'None': 'कोई नहीं',
    'Active': 'सक्रिय'
  }
};

// Substring replacements dictionary for dynamic strings
const substrings = {
  mr: {
    'Gate-In recorded': 'गेट-इन नोंदवले',
    'Intake completed': 'धान्य आवक पूर्ण',
    'deposited': 'जमा केले',
    'bags': 'गोण्या',
    'at': 'येथे',
    'Face Valuation': 'दर्शनी मूल्य',
    'generated for': 'यांच्यासाठी व्युत्पन्न',
    'dispatched': 'पाठवले',
    'via Vehicle': 'वाहनाद्वारे',
    'Weigh Bridge Gate-out weight certified': 'वे ब्रिज गेट-आउट वजन प्रमाणित',
    'NIC e-Way Bill generated & synchronized': 'NIC ई-वे बिल जनरेट आणि सिंक केले',
    'Delivery e-POD completed & signed': 'डिलिव्हरी ई-पीओडी पूर्ण आणि स्वाक्षरीकृत',
    'Delivery e-POD check in-transit': 'डिलिव्हरी ई-पीओडी इन-ट्रांझिट तपासा',
    'Dispatch Note Created': 'प्रेषण नोंद तयार केली',
    'Dispatch Note': 'प्रेषण नोंद',
    'created': 'तयार केले',
    'approved': 'मंजूर केले',
    'pledge loan of': 'तारण कर्ज',
    'approved pledge loan of': 'तारण कर्ज मंजूर केले',
    'for e-WR': 'ई-डब्ल्यूआर साठी',
    'Account funded': 'खात्यात जमा',
    'Financial Lien': 'वित्तीय धारणाधिकार (Lien)',
    'Requested collateral credit loan of': 'कृषी-पत तारण कर्जासाठी विनंती केली',
    'from': 'कडून',
    'Lab Certified': 'लॅब प्रमाणित',
    'quality grade updated to': 'गुणवत्ता श्रेणी सुधारित केली',
    'Logistics': 'लॉजिस्टिक्स',
    'reserved & queued for Outbound Weighbridge gate-out': 'राखीव आणि वजनकाट्यासाठी रांगेत',
    'released': 'मुक्त केले',
    'payment released': 'पेमेंट मुक्त केले',
    'Lien released': 'धारणमुक्त (Lien released)',
    'Purchase Order': 'खरेदी ऑर्डर',
    'accepted from': 'यांच्याकडून स्वीकृत',
    'Quality alert': 'गुणवत्ता इशारा',
    'moisture': 'आर्द्रता',
    'exceeds threshold': 'मर्यादेपेक्षा जास्त',
    'Aeration required': 'हवा खेळती करणे आवश्यक',
    'Returned due to critical moisture': 'अति आर्द्रतेमुळे परत केले',
    'Needs prompt aeration': 'तात्काळ हवेची गरज',
    'Registered successfully': 'यशस्वीरित्या नोंदणी केली',
    'Rice': 'तांदूळ',
    'Wheat': 'गहू',
    'Soybean': 'सोयाबीन',
    'Onion': 'कांदा',
    'Groundnut': 'भुईमूग',
    'Grade A': 'श्रेणी A',
    'Grade B': 'श्रेणी B',
    'Rejected': 'अस्वीकृत',
    'Wai FPO': 'वाई FPO',
    'Phaltan FPO': 'फलटण FPO',
    'Baramati FPO': 'बारामती FPO',
    'Satara Aggregator': 'सातारा संकलक',
    'Satara Aggregators': 'सातारा संकलक',
    'Raigad Mart': 'रायगड मार्ट',
    'FPO Manager': 'FPO व्यवस्थापक',
    'Farmer': 'शेतकरी',
    'Aggregator Buyer': 'संकलक खरेदीदार',
    'Market Partner': 'बाजार भागीदार'
  },
  hi: {
    'Gate-In recorded': 'गेट-इन दर्ज',
    'Intake completed': 'अनाज आवक पूर्ण',
    'deposited': 'जमा किया',
    'bags': 'बोरी',
    'at': 'पर',
    'Face Valuation': 'अंकित मूल्य',
    'generated for': 'के लिए जनरेट',
    'dispatched': 'भेजा गया',
    'via Vehicle': 'वाहन द्वारा',
    'Weigh Bridge Gate-out weight certified': 'वे ब्रिज गेट-आउट वजन प्रमाणित',
    'NIC e-Way Bill generated & synchronized': 'NIC ई-वे बिल जनरेट और सिंक किया',
    'Delivery e-POD completed & signed': 'डिलिवरी ई-पीओडी पूर्ण और हस्ताक्षरित',
    'Delivery e-POD check in-transit': 'डिलिवरी ई-पीओडी इन-ट्रांजिट जांचें',
    'Dispatch Note Created': 'प्रेषण नोट बनाया गया',
    'Dispatch Note': 'प्रेषण नोट',
    'created': 'बनाया गया',
    'approved': 'स्वीकृत',
    'pledge loan of': 'बंधक ऋण',
    'approved pledge loan of': 'बंधक ऋण स्वीकृत किया',
    'for e-WR': 'ई-डब्ल्यूआर के लिए',
    'Account funded': 'खाते में जमा',
    'Financial Lien': 'वित्तीय धारणाधिकार (Lien)',
    'Requested collateral credit loan of': 'कृषि-ऋण के लिए अनुरोध किया',
    'from': 'से',
    'Lab Certified': 'लैब प्रमाणित',
    'quality grade updated to': 'गुणवत्ता श्रेणी को बदलकर किया गया',
    'Logistics': 'लॉजिस्टिक्स',
    'reserved & queued for Outbound Weighbridge gate-out': 'आरक्षित और वे-ब्रिज के लिए कतारबद्ध',
    'released': 'मुक्त किया',
    'payment released': 'भुगतान जारी किया',
    'Lien released': 'बंधक मुक्त (Lien released)',
    'Purchase Order': 'क्रय आदेश',
    'accepted from': 'से स्वीकृत',
    'Quality alert': 'गुणवत्ता चेतावनी',
    'moisture': 'नमी',
    'exceeds threshold': 'सीमा से अधिक',
    'Aeration required': 'वातन आवश्यक',
    'Returned due to critical moisture': 'अत्यधिक नमी के कारण वापस किया',
    'Needs prompt aeration': 'त्वरित वातन की आवश्यकता',
    'Registered successfully': 'सफलतापूर्वक पंजीकृत',
    'Rice': 'चावल',
    'Wheat': 'गेहूं',
    'Soybean': 'सोयाबीन',
    'Onion': 'प्याज़',
    'Groundnut': 'मूंगफली',
    'Grade A': 'ग्रेड A',
    'Grade B': 'ग्रेड B',
    'Rejected': 'अस्वीकृत',
    'Wai FPO': 'वाई FPO',
    'Phaltan FPO': 'फलटण FPO',
    'Baramati FPO': 'बारामती FPO',
    'Satara Aggregator': 'सतारा संकलक',
    'Satara Aggregators': 'सतारा संकलक',
    'Raigad Mart': 'रायगढ़ मार्ट',
    'FPO Manager': 'FPO प्रबंधक',
    'Farmer': 'किसान',
    'Aggregator Buyer': 'संकलक क्रेता',
    'Market Partner': 'बाजार भागीदार'
  }
};

export const getTranslation = (key, lang = 'en') => {
  const currentLang = translations[lang] || translations['en'];
  return currentLang[key] || key;
};

export const getSubstringsDict = () => {
  return substrings;
};
