"""initial_schema_13_tables

Revision ID: 8ea249abd424
Revises: 
Create Date: 2026-06-09 13:01:47.278045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea249abd424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_mr', sa.String(length=100), nullable=True),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fpos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('aggregator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregator_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'fpo_staff', 'fpo_manager', 'aggregator', 'market_partner', 'admin', name='userrole'), nullable=False),
    sa.Column('initials', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('fpo', 'aggregator', 'cold_storage', name='warehousetype'), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=False),
    sa.Column('geo_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('capacity_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('permitted_commodities', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('intake', 'dispatch', 'qc', 'market', 'system', name='activitytype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmer_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('aadhaar', sa.String(length=20), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('fpo_id', sa.Integer(), nullable=False),
    sa.Column('total_deposit_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_code', sa.String(length=30), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_mt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'fulfilled', 'cancelled', name='postatus'), nullable=False),
    sa.Column('grn_id', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'confirmed', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_code')
    )
    op.create_table('commodity_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_code', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bag_count', sa.Integer(), nullable=False),
    sa.Column('moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grade', sa.Enum('grade_a', 'grade_b', 'grade_c', 'rejected', 'pending', name='gradeenum'), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'qc_pending', 'in_transit', 'delivered', 'returned', name='lotstatus'), nullable=False),
    sa.Column('intake_type', sa.Enum('walk_in', 'pre_registered', name='intaketype'), nullable=False),
    sa.Column('source_gps_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source_gps_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('intake_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_code')
    )
    op.create_table('dispatch_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dn_code', sa.String(length=30), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('commodity_desc', sa.String(length=200), nullable=False),
    sa.Column('quantity_desc', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg', sa.String(length=20), nullable=False),
    sa.Column('traccar_device_id', sa.String(length=50), nullable=True),
    sa.Column('fleetbase_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('created', 'in_transit', 'delivered', 'cancelled', name='dispatchstatus'), nullable=False),
    sa.Column('e_way_bill_no', sa.String(length=50), nullable=True),
    sa.Column('delivery_pod_url', sa.String(length=500), nullable=True),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['commodity_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dn_code')
    )
    op.create_table('quality_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qc_code', sa.String(length=30), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('moisture_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('foreign_matter_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('broken_grain_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grade_awarded', sa.Enum('grade_a', 'grade_b', 'grade_c', 'rejected', name='qcgrade'), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['commodity_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qc_code')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_code', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('intake', 'transfer', 'dispatch', 'return_', 'adjustment', name='movementtype'), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['commodity_lots.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_code')
    )
    op.create_table('warehouse_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wr_code', sa.String(length=30), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('valuation', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collateral_status', sa.Enum('none', 'applied', 'disbursed', 'released', name='collateralstatus'), nullable=False),
    sa.Column('pledge_bank', sa.String(length=100), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'amended', 'withdrawn', 'expired', name='wrstatus'), nullable=False),
    sa.Column('enam_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['commodity_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wr_code')
    )
    op.create_table('dispatch_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_note_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_note_id'], ['dispatch_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_timeline_events')
    op.drop_table('warehouse_receipts')
    op.drop_table('stock_movements')
    op.drop_table('quality_records')
    op.drop_table('dispatch_notes')
    op.drop_table('commodity_lots')
    op.drop_table('purchase_orders')
    op.drop_table('farmers')
    op.drop_table('activity_logs')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('fpos')
    op.drop_table('commodities')
    # ### end Alembic commands ###
