"""add_version_and_idempotency

Revision ID: a156543b1b77
Revises: a59a0106ac37
Create Date: 2026-06-15 09:59:35.630132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a156543b1b77'
down_revision: Union[str, Sequence[str], None] = 'a59a0106ac37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('commodity_lots', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('dispatch_notes', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('farmers', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('fpos', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('purchase_orders', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('stock_audits', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('warehouse_receipts', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'version')
    op.drop_column('warehouse_receipts', 'version')
    op.drop_column('users', 'version')
    op.drop_column('stock_audits', 'version')
    op.drop_column('purchase_orders', 'version')
    op.drop_column('fpos', 'version')
    op.drop_column('farmers', 'version')
    op.drop_column('dispatch_notes', 'version')
    op.drop_column('commodity_lots', 'version')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
