"""dispatch_quantity

Revision ID: a4a1a5da0ec8
Revises: 8ea249abd424
Create Date: 2026-06-14 07:05:08.585818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a1a5da0ec8'
down_revision: Union[str, Sequence[str], None] = '8ea249abd424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_notes', sa.Column('dispatch_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_notes', 'dispatch_quantity_kg')
    # ### end Alembic commands ###
