"""Add StockAudit table

Revision ID: a59a0106ac37
Revises: a4a1a5da0ec8
Create Date: 2026-06-14 09:57:53.919433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59a0106ac37'
down_revision: Union[str, Sequence[str], None] = 'a4a1a5da0ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'discrepancy', name='auditstatus'), nullable=False),
    sa.Column('system_stock_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_stock_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variance_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_audits')
    # ### end Alembic commands ###
