"""add destination lat lng to dispatch note

Revision ID: bff9d97b55e9
Revises: b3e7f1a2c4d6
Create Date: 2026-06-25 13:21:10.587522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff9d97b55e9'
down_revision: Union[str, Sequence[str], None] = 'b3e7f1a2c4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_notes', sa.Column('destination_lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('dispatch_notes', sa.Column('destination_lng', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_notes', 'destination_lng')
    op.drop_column('dispatch_notes', 'destination_lat')
    # ### end Alembic commands ###
